name: unit-test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Solidity unit test continuous integration
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment Setup
        uses: actions/setup-node@v3

      - name: Unit test
        uses: ambersun1234/hardhat-test-action@v1
        with:
          network: hardhat